name: Build and Publish Docker Images

on:
  push:
    branches:
      - emoji-notify
    # Only build the image when a file in the image is updated
    # These paths are files in the git repository from
    # .dockerignore (except the Docker files)
    paths-ignore:
      - ".devcontainer/**"
      - ".editorconfig"
      - ".github/**"
      - "!.github/workflows/docker.yml" # Still run on changes to this file
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - "**.md"
      - "config.example.json"
      - "config.schema.json"
      - "LICENSE"
      - "pyproject.toml"
      - "tests/**"

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set some tags
        id: vars
        run: |
          DATE_TAG=$(date +%Y%m%d)
          SHORT_SHA=${GITHUB_SHA::7}
          echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      - name: Build and push my version
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/auto-southwest-check-in:emoji-notify
            ${{ secrets.DOCKER_HUB_USERNAME }}/auto-southwest-check-in:${SHORT_SHA}
            ${{ secrets.DOCKER_HUB_USERNAME }}/auto-southwest-check-in:${DATE_TAG}
            ${{ secrets.DOCKER_HUB_USERNAME }}/auto-southwest-check-in:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max

